### ISSUE TITLE
Dependencies Issue

### ISSUE THREAD

**Issue by Komisian** [uxman-sherwani/react-native-fa-icons#1]
I got this error, how to solve this?

```
npm WARN react-native-maps@0.15.2 requires a peer of react@>=15.4.0 but none was installed.
npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.
npm WARN react-native-maps@0.15.2 requires a peer of react@>=15.4.0 but none was installed.

```
thank you

**Comment by uxxman** [comment]
Hi @Komisian,

These warnings are not regarding this library. These warnings come because your react-native project is using react version is 16.0.0-alpha, while  react-native-maps, lottie-react-native and react-native-branch is based on react version 15.x.x. You can still use them without any issues.

Cheers.
